version: '3.9'
services:
  shipment_backend:
    build: .
    ports:
      - 8005:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - shipment_db
    networks:
      - shipment
      - kafka

  shipment_queue:
    build: .
    command: 'php artisan queue:work --queue=shipment_topic'
    depends_on:
      - shipment_db
    networks:
      - shipment
      - kafka

  shipment_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: shipment
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - shipment

networks:
  kafka:
    external: true
  shipment: