version: '3.9'
services:
  customer_backend:
    build: .
    ports:
      - 8004:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - customer_db
    networks:
      - customer
      - kafka

  customer_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: customer
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - customer

networks:
  kafka:
    external: true
  customer: