version: '3.9'
services:
  products_backend:
    build: .
    ports:
      - 8003:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - products_db
    networks:
      - products
      - kafka

  products_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: products
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - products
      
networks:
  kafka:
    external: true
  products: