version: '3.9'
services:
  checkout_backend:
    build: .
    ports:
      - 8002:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - checkout_db
    networks:
      - checkout
      - kafka

  checkout_queue_customer:
    build: .
    command: 'php artisan queue:work --queue=customer_topic'
    depends_on:
      - checkout_db
    networks:
      - checkout
      - kafka

  checkout_queue_products:
    build: .
    command: 'php artisan queue:work --queue=products_topic'
    depends_on:
      - checkout_db
    networks:
      - checkout
      - kafka

  checkout_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - checkout

networks:
  kafka:
    external: true
  checkout: